%%% regroup the wind fields for each 3h analysis step (all altitudes in one file)
%%% the output file (all lat x all lon x all altitudes) individual for each
%%% 3h analysis (frcst time is imposed here to be ZERO hours)
%%% see .../Hymex/read_me.txt   : my documentation on grib-to-txt data
%%% conversion, and other matlab scripts
%%% read also : .../GRIB/documentation_AROME_WMED.txt

clear all
close all
startup
%%%% combine all txt files for all altitudes (one analysis moment only) into one file .mat 

data_description = {['aromewmed analysis every 3h (forecast step = 0h)'];...
    ['script:   read_aromewmed_all.mat'];...
    ['output_data_structure:  lat x lon x altitude'];...
    ['(1,1,1) = North/West/20m altitude'];...
    ['(521,1011,12) = Sout/East/3km altitude'];...
    ['generated by read_aromewmed_all.m'] }; 
    
core_dir = '/media/elena/SAMSUNG/AROME-WMED-REANALYSIS/';
listing = dir(fullfile(core_dir,'txtdata/')) ; % list of files within the folder
dout = fullfile(core_dir,'matfile/'); % where we store the output files

alti = [20,50,100, 250, 500,750,1000,1250,1500,2000,2500,3000]  ;% corresponding altitudes (within the GRIB file)
%%% "alti" regroups all the altitudes 

loni = dlmread(fullfile(core_dir,'txtdata/lon.txt'), '\t');
lati = dlmread(fullfile(core_dir,'txtdata/lat.txt'), '\t'); % decimal degrees 


for i = 3 : length(listing)-2 % because the last three files are lon.txt, lat.txt and listing.txt
    if length(listing(i).name) > 7 % data file and not lat/lon matrix
            T(i,1) = str2num(listing(i).name(5:6))    ; % month
            T(i,2) = str2num(listing(i).name(7:8))    ; % day
            T(i,3) = str2num(listing(i).name(10:13))/100  ; % time of analysis in GMT
            T(i,4) = str2num(listing(i).name(15:18))/100  ; % step of the forecast +XX hours relative to the analysis time
            T(i,5) = sum(T(i,3:4))                    ; % forecast time in GMT     
            
            %%%% chose variables: 'U,'V','T','P','RH'            
            if listing(i).name(20) == 'U'
                T(i,6) = 1 ;
            elseif listing(i).name(20) == 'V'
                T(i,6) = 2 ;
            end
     listing(i).name
    end
end

fc = 0; % forecast time step 
         
for mon = 9 : 11  
        for day = 1 : eomday(2012,mon)
                for tm = 0 : 3 : 21   % time of analysis (hour of the day in GMT)
                        for param = 1 : 2
                            %%% get all file names for the same moment of a day  
                            clear lst U V mmon dday H flpath
                            lst = find(T(:,1) == mon & T(:,2) == day & T(:,3) == tm & T(:,4) == fc & T(:,6) == param );
%                             listing(lst).name   
                            V = nan([521 1011 length(alti)]);
                            U = nan([521 1011 length(alti)]);

                            if ~isempty(lst) 
                                    for j = 1:length(lst) % each .txt file within lst list corresponds to some altitude
                                        clear l data a
                                        a = str2num(listing(lst(j)).name(22:25))  ; % altitude
                                        l = find(alti == a)  ; % altitude in 3rd dimention (depth of the matrice)
                                        data = dlmread(fullfile(core_dir,'txtdata/',listing(lst(j)).name), '\t');

                                        if param == 1
                                            U(:,:,l) = data;
                                        elseif param == 2
                                            V(:,:,l) = data;
                                        end
                                    end % frcts time == 0h                                                         
                              
                                  if mon < 10
                                          mmon = [num2str(0), num2str(mon)];
                                  else
                                          mmon = num2str(mon);
                                  end

                                  if day < 10
                                          dday = [num2str(0), num2str(day)];
                                  else
                                          dday = num2str(day);
                                  end

                                  if tm < 10
                                          H = [num2str(0), num2str(tm)];
                                  else
                                          H = num2str(tm);
                                  end

                                  
                                  if param == 1
    %                                     ['aromewmed_analysis_2012', mmon, dday, '_' , H, 'GMT_U.mat']                                    
                                        flpath = fullfile(dout,['aromewmed_analysis_2012', mmon, dday, '_' , H, 'GMT_U.mat'])
                                        save(flpath,'U','lati','loni','alti','day','mon','data_description' );
                                  elseif param == 2
                                        flpath = fullfile(dout,['aromewmed_analysis_2012', mmon, dday, '_' , H, 'GMT_V.mat'])
                                        save(flpath,'V','lati','loni','alti','day','mon','data_description' );
                                  end    
                                  
                            end % file selection (dd, month, var)    
                        end % U/V
                end % time of the day (analysis every 3h)     
        end % day 
end % month

% clear all
% close all
% load(/media/elena/SAMSUNG/AROME-WMED-REANALYSIS/matfile/aromewmed_analysis_20120905_00GMT_U.mat)
% what

